### PR TITLE
Configure Fester's default A/V thumbnail URLs

### PR DESCRIPTION
**Pull request by markmatney**
See https://github.com/UCLALibrary/fester/pull/186 for context.

### CODE REVIEW

**Comment by cachemeoutside** [comment]
@markmatney: This also needs to be applied to iiif/prod-iiif-values.yaml

**Comment by markmatney** [comment]
I think it doesn't though, because these variables are only read on ingest

**Comment by markmatney** [comment]
Oh, I see what you mean now

**Review by DRickard — APPROVED** [review]

**Comment by cachemeoutside** [comment]
LGTM! Looks good

**Review by cachemeoutside — APPROVED** [review]

**Pull request merged**
